// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.44
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SolutionScribe
{
    internal sealed partial class Vsix
    {
        public const string Id = "SolutionScribe.f6ef388d-6547-4b96-80a6-148ea664e35c";
        public const string Name = "Solution Scribe";
        public const string Description = @"Quickly and easily create LICENSE, README, CONTRIBUTIONS, and RELEASE_NOTES documents for your solutions.Create ";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Scott Lilly";
        public const string Tags = "";
        public const bool IsPreview = false;
    }
}
