// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.44
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SolutionScribe
{
    internal sealed partial class Vsix
    {
        public const string Id = "SolutionScribe.7b1276f1-14cd-44a0-bd5f-107fc5ec0015";
        public const string Name = "Solution Scribe";
        public const string Description = @"Create README, LICENSE, CHANGELOG, CONTRIBUTING, CODE_OF_CONDUCT and SECURITY files, and GitHub issue and pull request templates, for the solution you have open.";
        public const string Language = "en-US";
        public const string Version = "1.1.0";
        public const string Author = "Scott Lilly";
        public const string Tags = "documentation, readme, license, changelog, contributing, code of conduct, security, github, solution, scaffolding";
        public const bool IsPreview = false;
    }
}
