// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.44
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SolutionScribe
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidSolutionScribePkgString = "f1a2b3c4-d5e6-7890-abcd-ef1234567890";
        public static Guid guidSolutionScribePkg = new Guid(guidSolutionScribePkgString);

        public const string guidSolutionScribeCmdSetString = "a1b2c3d4-e5f6-7890-abcd-ef1234567890";
        public static Guid guidSolutionScribeCmdSet = new Guid(guidSolutionScribeCmdSetString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int SolutionScribeMenuGroup = 0x1000;
        public const int SolutionScribeMenu = 0x1001;
        public const int SolutionScribeSubMenuGroup = 0x1002;
        public const int CreateReadmeCommandId = 0x0100;
        public const int CreateLicenseCommandId = 0x0101;
        public const int CreateContributingCommandId = 0x0102;
        public const int CreateChangeLogCommandId = 0x0103;
    }
}
